// These are all variables generated from GUI in the world editor
// need to use those here to make the jasshelper build command work
globals
    camerasetup gg_cam_HeroSelectCamera= null
    trigger gg_trg_DraftInit= null

    force udg_PlayersWithHero= null
    real udg_Camera_Distance= 0
    integer udg_Draft_NODraftSpells= 0
    player udg_Draft_TempPlayer= null
    unit array udg_Draft_DraftBuildings
    unit array udg_Draft_UpgradeBuildings
    force udg_Draft_PlayersInGame= null
    hashtable udg_Draft_PlayerSpells= null
    integer array udg_Draft_PlayerSpellsMaxIndex
    integer array udg_Draft_NOSpellsLearned
    integer array udg_Draft_DefaultSpells
    integer udg_Draft_DefaultSpellsMaxIndex= 0
    integer udg_Draft_DraftBuilding= 0
    integer udg_Draft_UpgradeBuilding= 0
    trigger udg_Draft_TrgOnBuy= null
    real udg_DamageEventArmorPierced= 0
    real udg_AfterDamageEvent= 0
    boolean udg_DamageEventOverride= false
    real udg_DamageEvent= 0
    real udg_DamageModifierEvent= 0
    real udg_DamageEventAmount= 0
    unit udg_DamageEventSource= null
    unit udg_DamageEventTarget= null
    real udg_DamageEventPrevAmt= 0
    real udg_LethalDamageEvent= 0
    real udg_LethalDamageHP= 0
    real udg_AOEDamageEvent= 0
    unit udg_AOEDamageSource= null
    integer udg_DamageEventAOE= 0
    group udg_DamageEventAOEGroup= null
    integer udg_DamageEventLevel= 0
    unit udg_EnhancedDamageTarget= null
    integer udg_DamageEventType= 0
    boolean udg_NextDamageIsAttack= false
    boolean udg_NextDamageIsRanged= false
    boolean udg_NextDamageIsMelee= false
    integer udg_NextDamageType= 0
    integer udg_NextDamageWeaponT= 0
    real udg_DamageScalingUser= 0
    real udg_DamageScalingWC3= 0
    integer udg_DamageTypeBlocked= 0
    integer udg_DamageTypeCriticalStrike= 0
    integer udg_DamageTypeCode= 0
    integer udg_DamageTypeExplosive= 0
    integer udg_DamageTypeHeal= 0
    integer udg_DamageTypePure= 0
    integer udg_DamageTypePureExplosive= 0
    integer udg_DamageTypeReduced= 0
    trigger udg_DamageEventTrigger= null
    boolean udg_IsDamageAttack= false
    boolean udg_IsDamageMelee= false
    boolean udg_IsDamageRanged= false
    boolean udg_IsDamageSpell= false
    boolean udg_IsDamageCode= false
    unit udg_DamageFilterSource= null
    unit udg_DamageFilterTarget= null
    integer udg_DamageFilterAttackT= 0
    integer udg_DamageFilterDamageT= 0
    integer udg_DamageFilterSourceT= 0
    integer udg_DamageFilterTargetT= 0
    integer udg_DamageFilterSourceB= 0
    integer udg_DamageFilterTargetB= 0
    integer udg_DamageFilterType= 0
    real udg_DamageFilterMinAmount= 0
    integer udg_DamageEventArmorT= 0
    integer udg_ARMOR_TYPE_NONE= 0
    integer udg_ARMOR_TYPE_FLESH= 0
    integer udg_ARMOR_TYPE_METAL= 0
    integer udg_ARMOR_TYPE_WOOD= 0
    integer udg_ARMOR_TYPE_ETHEREAL= 0
    integer udg_ARMOR_TYPE_STONE= 0
    string array udg_ArmorTypeDebugStr
    attacktype array udg_CONVERTED_ATTACK_TYPE
    integer udg_DamageEventAttackT= 0
    integer udg_ATTACK_TYPE_SPELLS= 0
    integer udg_ATTACK_TYPE_NORMAL= 0
    integer udg_ATTACK_TYPE_PIERCE= 0
    integer udg_ATTACK_TYPE_SIEGE= 0
    integer udg_ATTACK_TYPE_MAGIC= 0
    integer udg_ATTACK_TYPE_CHAOS= 0
    integer udg_ATTACK_TYPE_HERO= 0
    string array udg_AttackTypeDebugStr
    damagetype array udg_CONVERTED_DAMAGE_TYPE
    integer udg_DamageEventDamageT= 0
    integer udg_DAMAGE_TYPE_UNKNOWN= 0
    integer udg_DAMAGE_TYPE_NORMAL= 0
    integer udg_DAMAGE_TYPE_ENHANCED= 0
    integer udg_DAMAGE_TYPE_FIRE= 0
    integer udg_DAMAGE_TYPE_COLD= 0
    integer udg_DAMAGE_TYPE_LIGHTNING= 0
    integer udg_DAMAGE_TYPE_POISON= 0
    integer udg_DAMAGE_TYPE_DISEASE= 0
    integer udg_DAMAGE_TYPE_DIVINE= 0
    integer udg_DAMAGE_TYPE_MAGIC= 0
    integer udg_DAMAGE_TYPE_SONIC= 0
    integer udg_DAMAGE_TYPE_ACID= 0
    integer udg_DAMAGE_TYPE_FORCE= 0
    integer udg_DAMAGE_TYPE_DEATH= 0
    integer udg_DAMAGE_TYPE_MIND= 0
    integer udg_DAMAGE_TYPE_PLANT= 0
    integer udg_DAMAGE_TYPE_DEFENSIVE= 0
    integer udg_DAMAGE_TYPE_DEMOLITION= 0
    integer udg_DAMAGE_TYPE_SLOW_POISON= 0
    integer udg_DAMAGE_TYPE_SPIRIT_LINK= 0
    integer udg_DAMAGE_TYPE_SHADOW_STRIKE= 0
    integer udg_DAMAGE_TYPE_UNIVERSAL= 0
    string array udg_DamageTypeDebugStr
    integer udg_DamageEventDefenseT= 0
    integer udg_DEFENSE_TYPE_LIGHT= 0
    integer udg_DEFENSE_TYPE_MEDIUM= 0
    integer udg_DEFENSE_TYPE_HEAVY= 0
    integer udg_DEFENSE_TYPE_FORTIFIED= 0
    integer udg_DEFENSE_TYPE_NORMAL= 0
    integer udg_DEFENSE_TYPE_HERO= 0
    integer udg_DEFENSE_TYPE_DIVINE= 0
    integer udg_DEFENSE_TYPE_UNARMORED= 0
    string array udg_DefenseTypeDebugStr
    string array udg_WeaponTypeDebugStr
    integer udg_WEAPON_TYPE_NONE= 0
    integer udg_WEAPON_TYPE_ML_CHOP= 0
    integer udg_WEAPON_TYPE_MM_CHOP= 0
    integer udg_WEAPON_TYPE_MH_CHOP= 0
    integer udg_WEAPON_TYPE_ML_SLICE= 0
    integer udg_WEAPON_TYPE_MM_SLICE= 0
    integer udg_WEAPON_TYPE_MH_SLICE= 0
    integer udg_WEAPON_TYPE_MM_BASH= 0
    integer udg_WEAPON_TYPE_MH_BASH= 0
    integer udg_WEAPON_TYPE_MM_STAB= 0
    integer udg_WEAPON_TYPE_MH_STAB= 0
    integer udg_WEAPON_TYPE_WL_SLICE= 0
    integer udg_WEAPON_TYPE_WM_SLICE= 0
    integer udg_WEAPON_TYPE_WH_SLICE= 0
    integer udg_WEAPON_TYPE_WL_BASH= 0
    integer udg_WEAPON_TYPE_WM_BASH= 0
    integer udg_WEAPON_TYPE_WH_BASH= 0
    integer udg_WEAPON_TYPE_WL_STAB= 0
    integer udg_WEAPON_TYPE_WM_STAB= 0
    integer udg_WEAPON_TYPE_CL_SLICE= 0
    integer udg_WEAPON_TYPE_CM_SLICE= 0
    integer udg_WEAPON_TYPE_CH_SLICE= 0
    integer udg_WEAPON_TYPE_AM_CHOP= 0
    integer udg_WEAPON_TYPE_RH_BASH= 0
    integer udg_DamageEventWeaponT= 0
endglobals